[package]
name = "srvrls"
version = "0.1.0"
authors = ["Dave Garred <dave.garred@serverlesstechnology.com>"]
edition = "2018"

[dependencies]
aws_lambda_events = "0.2.5"
lambda_runtime = "0.2.1"
serde = { version = "1.0.104", features = ["derive"]}
serde_json = "1.0"
